platform :ios, '7.0'
pod "AFNetworking", "~> 2.0"
pod 'RESideMenu'
pod 'SORelativeDateTransformer'
pod 'UITableView-NXEmptyView'
pod 'SVPullToRefresh'
pod 'AMAttributedHighlightLabel'
pod 'OvershareKit'
pod 'CJMTwitterFollowButton', '~>0.1.0'
pod 'SVProgressHUD'
pod 'MCSwipeTableViewCell'
pod 'CRToast', '~> 0.0.4'
pod 'MTBlockAlertView'
pod 'TTTAttributedLabel'